#!/bin/sh
./configure && make
cd src/gui
make menugenerator && ./make-lang
export INSTALL_ROOT=/tmp/pdfedit-package
strip pdfedit.exe
mkdir -p $INSTALL_ROOT
make install
cp -f ../../doc/README.cygwin $INSTALL_ROOT/readme.txt
cd ../..
VERSION=`./getversion`
cd $INSTALL_ROOT
echo 7z a -mx -r -tzip -x!*.bat -x!*.zip pdfedit-$VERSION-cygwin.zip >pack.bat
