#!/bin/sh
./configure && make
cd src/gui
make menugenerator && ./make-lang
export INSTALL_ROOT=/tmp/pdfedit-package
strip src/gui/pdfedit.exe
mkdir -p $INSTALL_ROOT
make install
cp -f ../../doc/README.cygwin $INSTALL_ROOT/readme.txt
cd $INSTALL_ROOT
echo 7z a -mx -r -tzip -x!*.bat -x!*.zip pdfedit >pack.bat