#!/bin/sh
#This file should be run on exported directory, not directly in CVS tree
#It is expected that the directory in which the sources are exported is named 'pdfedit'
#Make documentation before making tarball
(cd doc && make doc_dist)
(cd src/gui && lrelease pdfedit.pro)
#Get version number
VERSION=`./getversion`
#Pack all files, excluding unwanted ones (CVS files, generated programmer documentation, object files, binaries, etc ...)
rm ../pdfedit-$VERSION
ln -s pdfedit ../pdfedit-$VERSION
cd ..
tar -czvhf pdfedit-$VERSION.tar.gz pdfedit-$VERSION/* --exclude-from=pdfedit/dist-exclude
tar -cjvhf pdfedit-$VERSION.tar.bz2 pdfedit-$VERSION/* --exclude-from=pdfedit/dist-exclude
