#!/bin/sh
# This is script that will create distribution tarballs

# This file should be run on exported directory, not directly in CVS tree
# It is expected that the directory in which the sources are exported is named 
# 'pdfedit'

# Terminate on any error, so if something fails, broken or incomplete packages won't be generated
set -e

# Target path is directory where we want to create distribution tarballs
TARGET_PATH="../"
if [ $# -gt 0 ]
then
	[ -d $1 ] && TARGET_PATH="${1}/"
fi

# This directory
RELEASE_DIR=`pwd`

AUTOCONF=`which autoconf`

# creates release timestamp
./getversion -t > release_stamp

# Checks for configure script and generates it if either
# existing one is older than configure.in or it doesn't exist at all
if [ ! -x configure -o configure -ot configure.in ]
then
	if [ ! -x $AUTOCONF ]
	then
		echo Autoconf not found.
		exit 1
	fi
	echo Generating configure script
	RESULT=OK
	$AUTOCONF || RESULT=FAILED
	echo $RESULT
	if [ "$RESULT" = "FAILED" ]
	then
		echo Unable to generate configure script
		exit 1
	fi
fi
# generates online help
tools/generate_online_help.sh doc src/gui
echo Online help generated

# generates man page
cd doc/tools/
./docbook2man.pl ../user/pdfedit.xml > ../user/pdfedit.1
cd ../../
echo Man page generated

#Get version number
VERSION=`./getversion -v`
#Pack all files, excluding unwanted ones (CVS files, generated programmer documentation, object files, binaries, etc ...)
rm -f "${TARGET_PATH}pdfedit-$VERSION"
ln -s "${RELEASE_DIR}" "${TARGET_PATH}pdfedit-$VERSION"
cd "${TARGET_PATH}"


# creates distribution tarball
tar -czhf "pdfedit-$VERSION.tar.gz" "pdfedit-$VERSION"/* --exclude-from="pdfedit-$VERSION/dist-exclude"
echo pdfedit-$VERSION.tar.gz created
tar -cjhf "pdfedit-$VERSION.tar.bz2" "pdfedit-$VERSION"/* --exclude-from="pdfedit-$VERSION/dist-exclude"
echo pdfedit-$VERSION.tar.bz2 created

cd "$RELEASE_DIR"
rm "${TARGET_PATH}pdfedit-${VERSION}"
