#!/bin/sh
# PDFedit - free program for PDF document manipulation.
# Copyright (C) 2006-2009  PDFedit team: Michal Hocko,
#                                        Jozef Misutka,
#                                        Martin Petricek
#                   Former team members: Miroslav Jahoda
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (in doc/LICENSE.GPL); if not, write to the 
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Project is hosted on http://sourceforge.net/projects/pdfedit

# Run in sufficiently empty directory!

TARBALL=`pwd`/tarball
fail_cleanup()
{
	if [ -d $TARBALL ]
	then
		echo cleaning $TARBALL directory
		rm -rf $TARBALL
	fi
	exit 1
}

# Terminate on any error
set -e

if [ -z $CVSROOT ]
then
  echo CVSROOT is not defined
  exit 1
fi

# Reasonable umask for files
umask 022
if [ -e $TARBALL ]
then
 echo directory $TARBALL already exist
 exit 1
fi

# Export CVS sources into "$TARBALL" directory
mkdir $TARBALL
cd $TARBALL
cvs export -D now pdfedit || fail_cleanup
cd pdfedit
# Generate files that should be in the distribution by default
./makedist
cd ..

echo Do not forget to tag CVS:
echo Use:
echo " cvs tag RELEASE_X_Y_Z"
echo "in cvs root dir"

