#!/bin/sh

#run in sufficiently empty directory!

umask 022
if [ -e tarball ]
then
echo directory tarball already exist
exit 1
fi

mkdir tarball
cd tarball
cvs export -D now pdfedit
cd pdfedit
./makedist
cd ..

echo Do not forget to tag CVS:
echo Use:
echo " cvs tag RELEASE_X_Y_Z"
echo "in cvs root dir"

