#!/bin/sh
# PDFedit - free program for PDF document manipulation.
# Copyright (C) 2006-2009  PDFedit team: Michal Hocko,
#                                        Jozef Misutka,
#                                        Martin Petricek
#                   Former team members: Miroslav Jahoda
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (in doc/LICENSE.GPL); if not, write to the 
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA  02111-1307  USA
#
# Project is hosted on http://sourceforge.net/projects/pdfedit

# Check release before actually releasing

#TODO: unpack tarball elsewhere, run checks on unpacked stuff

error=0

#Check completeness of translations

check_trans() {
 all=`grep '<message>' <$1 |wc -l`
 un=`grep 'type="unfinished"' <$1 |wc -l`
 obs=`grep 'type="obsolete"' <$1 |wc -l`
 pct=$((100-100*un/(all-obs)))
 echo "$1 $all messages, $un unfinished, $obs obsolete, $pct% complete"
 if test ! $un -eq 0
 then
  error=1
 fi
}

echo "Checking translations"
cd src/gui/lang
for i in *.ts
do
 check_trans $i
done

# Return results of check

if test $error -eq 0
then
 echo "Everything is OK"
else
 echo "Some errors encountered"
fi

exit $error
